services:
  app:
    image: ghcr.io/rayanmelzi/wisdom-from-quran:${TAG:-latest}
    container_name: wisdom-from-quran
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env